/**
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.ui.contentassist;

import org.chabu.hwmap.ui.contentassist.AbstractHwMapDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class HwMapDslProposalProvider extends AbstractHwMapDslProposalProvider {
}
