/**
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap;

import org.chabu.hwmap.AbstractHwMapDslRuntimeModule;
import org.chabu.hwmap.CommonValueConverter;
import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class HwMapDslRuntimeModule extends AbstractHwMapDslRuntimeModule {
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return CommonValueConverter.class;
  }
}
