/*
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HwMapDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/chabu/hwmap/parser/antlr/internal/InternalHwMapDsl.tokens");
	}
}
