/*
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.parser.antlr;

import com.google.inject.Inject;
import org.chabu.hwmap.parser.antlr.internal.InternalHwMapDslParser;
import org.chabu.hwmap.services.HwMapDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class HwMapDslParser extends AbstractAntlrParser {

	@Inject
	private HwMapDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHwMapDslParser createParser(XtextTokenStream stream) {
		return new InternalHwMapDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MemoryMap";
	}

	public HwMapDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HwMapDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
