/*
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HwMapDslStandaloneSetup extends HwMapDslStandaloneSetupGenerated {

	def static void doSetup() {
		new HwMapDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
