/*
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap

import org.eclipse.xtext.conversion.IValueConverterService

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class HwMapDslRuntimeModule extends AbstractHwMapDslRuntimeModule {

	override Class<? extends IValueConverterService> bindIValueConverterService() {
		return CommonValueConverter
	}
}
