/**
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.hwMapDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.chabu.hwmap.hwMapDsl.Block#getName <em>Name</em>}</li>
 *   <li>{@link org.chabu.hwmap.hwMapDsl.Block#getSize <em>Size</em>}</li>
 *   <li>{@link org.chabu.hwmap.hwMapDsl.Block#getRegs <em>Regs</em>}</li>
 * </ul>
 *
 * @see org.chabu.hwmap.hwMapDsl.HwMapDslPackage#getBlock()
 * @model
 * @generated
 */
public interface Block extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.chabu.hwmap.hwMapDsl.HwMapDslPackage#getBlock_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.chabu.hwmap.hwMapDsl.Block#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(Integer)
   * @see org.chabu.hwmap.hwMapDsl.HwMapDslPackage#getBlock_Size()
   * @model
   * @generated
   */
  Integer getSize();

  /**
   * Sets the value of the '{@link org.chabu.hwmap.hwMapDsl.Block#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(Integer value);

  /**
   * Returns the value of the '<em><b>Regs</b></em>' containment reference list.
   * The list contents are of type {@link org.chabu.hwmap.hwMapDsl.Register}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Regs</em>' containment reference list.
   * @see org.chabu.hwmap.hwMapDsl.HwMapDslPackage#getBlock_Regs()
   * @model containment="true"
   * @generated
   */
  EList<Register> getRegs();

} // Block
