/**
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.hwMapDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.chabu.hwmap.hwMapDsl.HwMapDslFactory
 * @model kind="package"
 * @generated
 */
public interface HwMapDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "hwMapDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.chabu.org/hwmap/HwMapDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "hwMapDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HwMapDslPackage eINSTANCE = org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.chabu.hwmap.hwMapDsl.impl.MemoryMapImpl <em>Memory Map</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.chabu.hwmap.hwMapDsl.impl.MemoryMapImpl
   * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getMemoryMap()
   * @generated
   */
  int MEMORY_MAP = 0;

  /**
   * The feature id for the '<em><b>Outputs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORY_MAP__OUTPUTS = 0;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORY_MAP__COMPONENTS = 1;

  /**
   * The number of structural features of the '<em>Memory Map</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORY_MAP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.chabu.hwmap.hwMapDsl.impl.OutputImpl <em>Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.chabu.hwmap.hwMapDsl.impl.OutputImpl
   * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getOutput()
   * @generated
   */
  int OUTPUT = 1;

  /**
   * The feature id for the '<em><b>Mode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__MODE = 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__PATH = 1;

  /**
   * The number of structural features of the '<em>Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.chabu.hwmap.hwMapDsl.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.chabu.hwmap.hwMapDsl.impl.ComponentImpl
   * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 2;

  /**
   * The feature id for the '<em><b>Comp Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__COMP_NAME = 0;

  /**
   * The feature id for the '<em><b>Blocks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__BLOCKS = 1;

  /**
   * The feature id for the '<em><b>Insts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__INSTS = 2;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.chabu.hwmap.hwMapDsl.impl.InstantiationImpl <em>Instantiation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.chabu.hwmap.hwMapDsl.impl.InstantiationImpl
   * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getInstantiation()
   * @generated
   */
  int INSTANTIATION = 3;

  /**
   * The feature id for the '<em><b>Addr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTANTIATION__ADDR = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTANTIATION__TYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTANTIATION__NAME = 2;

  /**
   * The number of structural features of the '<em>Instantiation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTANTIATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.chabu.hwmap.hwMapDsl.impl.BlockImpl <em>Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.chabu.hwmap.hwMapDsl.impl.BlockImpl
   * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getBlock()
   * @generated
   */
  int BLOCK = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__NAME = 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__SIZE = 1;

  /**
   * The feature id for the '<em><b>Regs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__REGS = 2;

  /**
   * The number of structural features of the '<em>Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.chabu.hwmap.hwMapDsl.impl.RegisterImpl <em>Register</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.chabu.hwmap.hwMapDsl.impl.RegisterImpl
   * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getRegister()
   * @generated
   */
  int REGISTER = 5;

  /**
   * The feature id for the '<em><b>Addr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER__ADDR = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER__NAME = 1;

  /**
   * The feature id for the '<em><b>Consts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER__CONSTS = 2;

  /**
   * The feature id for the '<em><b>Bits</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER__BITS = 3;

  /**
   * The number of structural features of the '<em>Register</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.chabu.hwmap.hwMapDsl.impl.RegisterBitsImpl <em>Register Bits</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.chabu.hwmap.hwMapDsl.impl.RegisterBitsImpl
   * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getRegisterBits()
   * @generated
   */
  int REGISTER_BITS = 6;

  /**
   * The feature id for the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER_BITS__RANGE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER_BITS__NAME = 1;

  /**
   * The feature id for the '<em><b>Consts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER_BITS__CONSTS = 2;

  /**
   * The number of structural features of the '<em>Register Bits</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER_BITS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.chabu.hwmap.hwMapDsl.impl.RangeImpl <em>Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.chabu.hwmap.hwMapDsl.impl.RangeImpl
   * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getRange()
   * @generated
   */
  int RANGE = 7;

  /**
   * The feature id for the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__LEFT = 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__RIGHT = 1;

  /**
   * The number of structural features of the '<em>Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.chabu.hwmap.hwMapDsl.impl.ConstantImpl <em>Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.chabu.hwmap.hwMapDsl.impl.ConstantImpl
   * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getConstant()
   * @generated
   */
  int CONSTANT = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__VALUE = 0;

  /**
   * The number of structural features of the '<em>Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.chabu.hwmap.hwMapDsl.MemoryMap <em>Memory Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Memory Map</em>'.
   * @see org.chabu.hwmap.hwMapDsl.MemoryMap
   * @generated
   */
  EClass getMemoryMap();

  /**
   * Returns the meta object for the containment reference list '{@link org.chabu.hwmap.hwMapDsl.MemoryMap#getOutputs <em>Outputs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Outputs</em>'.
   * @see org.chabu.hwmap.hwMapDsl.MemoryMap#getOutputs()
   * @see #getMemoryMap()
   * @generated
   */
  EReference getMemoryMap_Outputs();

  /**
   * Returns the meta object for the containment reference list '{@link org.chabu.hwmap.hwMapDsl.MemoryMap#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see org.chabu.hwmap.hwMapDsl.MemoryMap#getComponents()
   * @see #getMemoryMap()
   * @generated
   */
  EReference getMemoryMap_Components();

  /**
   * Returns the meta object for class '{@link org.chabu.hwmap.hwMapDsl.Output <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Output
   * @generated
   */
  EClass getOutput();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.Output#getMode <em>Mode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mode</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Output#getMode()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_Mode();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.Output#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Output#getPath()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_Path();

  /**
   * Returns the meta object for class '{@link org.chabu.hwmap.hwMapDsl.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.Component#getCompName <em>Comp Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comp Name</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Component#getCompName()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_CompName();

  /**
   * Returns the meta object for the containment reference list '{@link org.chabu.hwmap.hwMapDsl.Component#getBlocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Blocks</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Component#getBlocks()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Blocks();

  /**
   * Returns the meta object for the containment reference list '{@link org.chabu.hwmap.hwMapDsl.Component#getInsts <em>Insts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Insts</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Component#getInsts()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Insts();

  /**
   * Returns the meta object for class '{@link org.chabu.hwmap.hwMapDsl.Instantiation <em>Instantiation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instantiation</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Instantiation
   * @generated
   */
  EClass getInstantiation();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.Instantiation#getAddr <em>Addr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Addr</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Instantiation#getAddr()
   * @see #getInstantiation()
   * @generated
   */
  EAttribute getInstantiation_Addr();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.Instantiation#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Instantiation#getType()
   * @see #getInstantiation()
   * @generated
   */
  EAttribute getInstantiation_Type();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.Instantiation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Instantiation#getName()
   * @see #getInstantiation()
   * @generated
   */
  EAttribute getInstantiation_Name();

  /**
   * Returns the meta object for class '{@link org.chabu.hwmap.hwMapDsl.Block <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Block
   * @generated
   */
  EClass getBlock();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.Block#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Block#getName()
   * @see #getBlock()
   * @generated
   */
  EAttribute getBlock_Name();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.Block#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Block#getSize()
   * @see #getBlock()
   * @generated
   */
  EAttribute getBlock_Size();

  /**
   * Returns the meta object for the containment reference list '{@link org.chabu.hwmap.hwMapDsl.Block#getRegs <em>Regs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Regs</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Block#getRegs()
   * @see #getBlock()
   * @generated
   */
  EReference getBlock_Regs();

  /**
   * Returns the meta object for class '{@link org.chabu.hwmap.hwMapDsl.Register <em>Register</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Register</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Register
   * @generated
   */
  EClass getRegister();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.Register#getAddr <em>Addr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Addr</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Register#getAddr()
   * @see #getRegister()
   * @generated
   */
  EAttribute getRegister_Addr();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.Register#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Register#getName()
   * @see #getRegister()
   * @generated
   */
  EAttribute getRegister_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.chabu.hwmap.hwMapDsl.Register#getConsts <em>Consts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Consts</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Register#getConsts()
   * @see #getRegister()
   * @generated
   */
  EReference getRegister_Consts();

  /**
   * Returns the meta object for the containment reference list '{@link org.chabu.hwmap.hwMapDsl.Register#getBits <em>Bits</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Bits</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Register#getBits()
   * @see #getRegister()
   * @generated
   */
  EReference getRegister_Bits();

  /**
   * Returns the meta object for class '{@link org.chabu.hwmap.hwMapDsl.RegisterBits <em>Register Bits</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Register Bits</em>'.
   * @see org.chabu.hwmap.hwMapDsl.RegisterBits
   * @generated
   */
  EClass getRegisterBits();

  /**
   * Returns the meta object for the containment reference '{@link org.chabu.hwmap.hwMapDsl.RegisterBits#getRange <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Range</em>'.
   * @see org.chabu.hwmap.hwMapDsl.RegisterBits#getRange()
   * @see #getRegisterBits()
   * @generated
   */
  EReference getRegisterBits_Range();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.RegisterBits#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.chabu.hwmap.hwMapDsl.RegisterBits#getName()
   * @see #getRegisterBits()
   * @generated
   */
  EAttribute getRegisterBits_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.chabu.hwmap.hwMapDsl.RegisterBits#getConsts <em>Consts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Consts</em>'.
   * @see org.chabu.hwmap.hwMapDsl.RegisterBits#getConsts()
   * @see #getRegisterBits()
   * @generated
   */
  EReference getRegisterBits_Consts();

  /**
   * Returns the meta object for class '{@link org.chabu.hwmap.hwMapDsl.Range <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Range</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Range
   * @generated
   */
  EClass getRange();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.Range#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Range#getLeft()
   * @see #getRange()
   * @generated
   */
  EAttribute getRange_Left();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.Range#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Range#getRight()
   * @see #getRange()
   * @generated
   */
  EAttribute getRange_Right();

  /**
   * Returns the meta object for class '{@link org.chabu.hwmap.hwMapDsl.Constant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constant</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Constant
   * @generated
   */
  EClass getConstant();

  /**
   * Returns the meta object for the attribute '{@link org.chabu.hwmap.hwMapDsl.Constant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.chabu.hwmap.hwMapDsl.Constant#getValue()
   * @see #getConstant()
   * @generated
   */
  EAttribute getConstant_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HwMapDslFactory getHwMapDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.chabu.hwmap.hwMapDsl.impl.MemoryMapImpl <em>Memory Map</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.chabu.hwmap.hwMapDsl.impl.MemoryMapImpl
     * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getMemoryMap()
     * @generated
     */
    EClass MEMORY_MAP = eINSTANCE.getMemoryMap();

    /**
     * The meta object literal for the '<em><b>Outputs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEMORY_MAP__OUTPUTS = eINSTANCE.getMemoryMap_Outputs();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEMORY_MAP__COMPONENTS = eINSTANCE.getMemoryMap_Components();

    /**
     * The meta object literal for the '{@link org.chabu.hwmap.hwMapDsl.impl.OutputImpl <em>Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.chabu.hwmap.hwMapDsl.impl.OutputImpl
     * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getOutput()
     * @generated
     */
    EClass OUTPUT = eINSTANCE.getOutput();

    /**
     * The meta object literal for the '<em><b>Mode</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__MODE = eINSTANCE.getOutput_Mode();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__PATH = eINSTANCE.getOutput_Path();

    /**
     * The meta object literal for the '{@link org.chabu.hwmap.hwMapDsl.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.chabu.hwmap.hwMapDsl.impl.ComponentImpl
     * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '<em><b>Comp Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__COMP_NAME = eINSTANCE.getComponent_CompName();

    /**
     * The meta object literal for the '<em><b>Blocks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__BLOCKS = eINSTANCE.getComponent_Blocks();

    /**
     * The meta object literal for the '<em><b>Insts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__INSTS = eINSTANCE.getComponent_Insts();

    /**
     * The meta object literal for the '{@link org.chabu.hwmap.hwMapDsl.impl.InstantiationImpl <em>Instantiation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.chabu.hwmap.hwMapDsl.impl.InstantiationImpl
     * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getInstantiation()
     * @generated
     */
    EClass INSTANTIATION = eINSTANCE.getInstantiation();

    /**
     * The meta object literal for the '<em><b>Addr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTANTIATION__ADDR = eINSTANCE.getInstantiation_Addr();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTANTIATION__TYPE = eINSTANCE.getInstantiation_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTANTIATION__NAME = eINSTANCE.getInstantiation_Name();

    /**
     * The meta object literal for the '{@link org.chabu.hwmap.hwMapDsl.impl.BlockImpl <em>Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.chabu.hwmap.hwMapDsl.impl.BlockImpl
     * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getBlock()
     * @generated
     */
    EClass BLOCK = eINSTANCE.getBlock();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOCK__NAME = eINSTANCE.getBlock_Name();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOCK__SIZE = eINSTANCE.getBlock_Size();

    /**
     * The meta object literal for the '<em><b>Regs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOCK__REGS = eINSTANCE.getBlock_Regs();

    /**
     * The meta object literal for the '{@link org.chabu.hwmap.hwMapDsl.impl.RegisterImpl <em>Register</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.chabu.hwmap.hwMapDsl.impl.RegisterImpl
     * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getRegister()
     * @generated
     */
    EClass REGISTER = eINSTANCE.getRegister();

    /**
     * The meta object literal for the '<em><b>Addr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGISTER__ADDR = eINSTANCE.getRegister_Addr();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGISTER__NAME = eINSTANCE.getRegister_Name();

    /**
     * The meta object literal for the '<em><b>Consts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGISTER__CONSTS = eINSTANCE.getRegister_Consts();

    /**
     * The meta object literal for the '<em><b>Bits</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGISTER__BITS = eINSTANCE.getRegister_Bits();

    /**
     * The meta object literal for the '{@link org.chabu.hwmap.hwMapDsl.impl.RegisterBitsImpl <em>Register Bits</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.chabu.hwmap.hwMapDsl.impl.RegisterBitsImpl
     * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getRegisterBits()
     * @generated
     */
    EClass REGISTER_BITS = eINSTANCE.getRegisterBits();

    /**
     * The meta object literal for the '<em><b>Range</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGISTER_BITS__RANGE = eINSTANCE.getRegisterBits_Range();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGISTER_BITS__NAME = eINSTANCE.getRegisterBits_Name();

    /**
     * The meta object literal for the '<em><b>Consts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGISTER_BITS__CONSTS = eINSTANCE.getRegisterBits_Consts();

    /**
     * The meta object literal for the '{@link org.chabu.hwmap.hwMapDsl.impl.RangeImpl <em>Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.chabu.hwmap.hwMapDsl.impl.RangeImpl
     * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getRange()
     * @generated
     */
    EClass RANGE = eINSTANCE.getRange();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE__LEFT = eINSTANCE.getRange_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE__RIGHT = eINSTANCE.getRange_Right();

    /**
     * The meta object literal for the '{@link org.chabu.hwmap.hwMapDsl.impl.ConstantImpl <em>Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.chabu.hwmap.hwMapDsl.impl.ConstantImpl
     * @see org.chabu.hwmap.hwMapDsl.impl.HwMapDslPackageImpl#getConstant()
     * @generated
     */
    EClass CONSTANT = eINSTANCE.getConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__VALUE = eINSTANCE.getConstant_Value();

  }

} //HwMapDslPackage
