/**
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.hwMapDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Memory Map</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.chabu.hwmap.hwMapDsl.MemoryMap#getOutputs <em>Outputs</em>}</li>
 *   <li>{@link org.chabu.hwmap.hwMapDsl.MemoryMap#getComponents <em>Components</em>}</li>
 * </ul>
 *
 * @see org.chabu.hwmap.hwMapDsl.HwMapDslPackage#getMemoryMap()
 * @model
 * @generated
 */
public interface MemoryMap extends EObject
{
  /**
   * Returns the value of the '<em><b>Outputs</b></em>' containment reference list.
   * The list contents are of type {@link org.chabu.hwmap.hwMapDsl.Output}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Outputs</em>' containment reference list.
   * @see org.chabu.hwmap.hwMapDsl.HwMapDslPackage#getMemoryMap_Outputs()
   * @model containment="true"
   * @generated
   */
  EList<Output> getOutputs();

  /**
   * Returns the value of the '<em><b>Components</b></em>' containment reference list.
   * The list contents are of type {@link org.chabu.hwmap.hwMapDsl.Component}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Components</em>' containment reference list.
   * @see org.chabu.hwmap.hwMapDsl.HwMapDslPackage#getMemoryMap_Components()
   * @model containment="true"
   * @generated
   */
  EList<Component> getComponents();

} // MemoryMap
