/**
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.hwMapDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Register</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.chabu.hwmap.hwMapDsl.Register#getAddr <em>Addr</em>}</li>
 *   <li>{@link org.chabu.hwmap.hwMapDsl.Register#getName <em>Name</em>}</li>
 *   <li>{@link org.chabu.hwmap.hwMapDsl.Register#getConsts <em>Consts</em>}</li>
 *   <li>{@link org.chabu.hwmap.hwMapDsl.Register#getBits <em>Bits</em>}</li>
 * </ul>
 *
 * @see org.chabu.hwmap.hwMapDsl.HwMapDslPackage#getRegister()
 * @model
 * @generated
 */
public interface Register extends EObject
{
  /**
   * Returns the value of the '<em><b>Addr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Addr</em>' attribute.
   * @see #setAddr(int)
   * @see org.chabu.hwmap.hwMapDsl.HwMapDslPackage#getRegister_Addr()
   * @model
   * @generated
   */
  int getAddr();

  /**
   * Sets the value of the '{@link org.chabu.hwmap.hwMapDsl.Register#getAddr <em>Addr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Addr</em>' attribute.
   * @see #getAddr()
   * @generated
   */
  void setAddr(int value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.chabu.hwmap.hwMapDsl.HwMapDslPackage#getRegister_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.chabu.hwmap.hwMapDsl.Register#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Consts</b></em>' containment reference list.
   * The list contents are of type {@link org.chabu.hwmap.hwMapDsl.Constant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consts</em>' containment reference list.
   * @see org.chabu.hwmap.hwMapDsl.HwMapDslPackage#getRegister_Consts()
   * @model containment="true"
   * @generated
   */
  EList<Constant> getConsts();

  /**
   * Returns the value of the '<em><b>Bits</b></em>' containment reference list.
   * The list contents are of type {@link org.chabu.hwmap.hwMapDsl.RegisterBits}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bits</em>' containment reference list.
   * @see org.chabu.hwmap.hwMapDsl.HwMapDslPackage#getRegister_Bits()
   * @model containment="true"
   * @generated
   */
  EList<RegisterBits> getBits();

} // Register
