/*
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.ui

import org.chabu.hwmap.ui.handler.GenerationHandler
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class HwMapDslUiModule extends AbstractHwMapDslUiModule {
	
	def Class<? extends GenerationHandler> bindUiGenerationHandler() {
		return GenerationHandler;
	}
	
}
