/**
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.tests;

import com.google.inject.Inject;
import org.chabu.hwmap.hwMapDsl.Component;
import org.chabu.hwmap.hwMapDsl.MemoryMap;
import org.chabu.hwmap.tests.HwMapDslInjectorProvider;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(HwMapDslInjectorProvider.class)
@SuppressWarnings("all")
public class HwMapDslParsingTest {
  @Inject
  private ParseHelper<MemoryMap> parseHelper;
  
  @Test
  public void exampleParsing() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Output VHDL \"../relpath\"");
      _builder.newLine();
      _builder.append("Output C    \"../relpath\"");
      _builder.newLine();
      _builder.newLine();
      _builder.append("Component CapSim {");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("// Register block for the main control");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("Block Regs 0x20 {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("// Register block for the main control");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("0x00 Control");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("0x04 Status");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("[   0] IRQ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("[7..4] Command");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("Constant 0x0 Nothing");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("Constant 0x1 Start");
      _builder.newLine();
      _builder.append("\t\t\t       ");
      _builder.append("Constant 0x2 Stop");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("0x08 ModVersion");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("Constant 0x12341200 Value");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("0x0A ModVersion");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("Block TraceMem 0x1000 {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("0x0000 Regs");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("0x1000 TraceMem TraceMem_A");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("0x2000 TraceMem TraceMem_B");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final MemoryMap result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void parseComponent() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Component CapSim {");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final MemoryMap result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
      Component _get = result.getComponents().get(0);
      final Component comp = ((Component) _get);
      Assertions.assertEquals("CapSim", comp.getCompName());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
