/*
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.ide

import com.google.inject.Guice
import org.chabu.hwmap.HwMapDslRuntimeModule
import org.chabu.hwmap.HwMapDslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class HwMapDslIdeSetup extends HwMapDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new HwMapDslRuntimeModule, new HwMapDslIdeModule))
	}
	
}
