/*
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractHwMapDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.chabu.hwmap.hwMapDsl.HwMapDslPackage.eINSTANCE);
		return result;
	}
}
