/**
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.validation;

import org.chabu.hwmap.validation.AbstractHwMapDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class HwMapDslValidator extends AbstractHwMapDslValidator {
}
