/**
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.chabu.hwmap.HwMapDslRuntimeModule;
import org.chabu.hwmap.HwMapDslStandaloneSetup;
import org.chabu.hwmap.ide.HwMapDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class HwMapDslIdeSetup extends HwMapDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    HwMapDslRuntimeModule _hwMapDslRuntimeModule = new HwMapDslRuntimeModule();
    HwMapDslIdeModule _hwMapDslIdeModule = new HwMapDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_hwMapDslRuntimeModule, _hwMapDslIdeModule));
  }
}
