/**
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.ide;

import org.chabu.hwmap.ide.AbstractHwMapDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class HwMapDslIdeModule extends AbstractHwMapDslIdeModule {
}
