/**
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.ui;

import org.chabu.hwmap.ui.AbstractHwMapDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class HwMapDslUiModule extends AbstractHwMapDslUiModule {
  public HwMapDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
