/*
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.ui.tests;

import com.google.inject.Injector;
import org.chabu.hwmap.ui.internal.HwmapActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class HwMapDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HwmapActivator.getInstance().getInjector("org.chabu.hwmap.HwMapDsl");
	}

}
