/*
 * generated by Xtext 2.19.0
 */
package org.chabu.hwmap.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHwMapDslScopeProvider extends DelegatingScopeProvider {
}
